name: "gitHubActions"


on: [push]

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
    - name: "Checking Out Repo"
      uses: actions/checkout@v4
    
    - name: "Installing cowsay package"
      run: sudo apt install cowsay

    - name: "Generating ASCII cowsay diagram"
      run: cowsay -f dragon "Run for cover, Am dragon" >> dragon.txt

    - name: "Uploading artifact"
      uses: actions/upload-artifact@v4
      with: 
        name: dragon-artifact
        path: dragon.txt

  Job2:
    needs: Job1
    runs-on: ubuntu-latest
    steps:
    - name: "Download my-artifact"
      uses: actions/download-artifact@v4
      with: 
        name: dragon-artifact

    - name: "Listing Files"
      run: ls -la

    - name: "Validating if file exist"
      run: grep -i "dragon" dragon.txt

  Job3:
    needs: Job2
    runs-on: ubuntu-latest
    steps:
    - name: "Download my-artifact"
      uses: actions/download-artifact@v4
      with:
        name: dragon-artifact

    - name: "Listing Files"
      run: ls -la

    - name: "Print Dragon.txt file"
      run: cat dragon.txt
