name: 'githubActions'

on: [push]

jobs:
  Job-1:
    runs-on: ubuntu-latest

    steps:
    - name: "Checking out my repo"
      uses: "actions/checkout@v6"

    - name: "Combined Step"
      run: | 
       echo "My First Step..."
       sleep 10
       touch newfile.txt
  
  Job-2:
    runs-on: ubuntu-latest

    steps:
    - name: "Listing Files"
      run: |
       ls -la
       chmod +x listing-file.sh
       ./listing-file
