name: 'githubActions'

on: [push]

jobs:
  Job-1:
    runs-on: ubuntu-latest

    steps:
    - name: "Checking out my repo"
      uses: "actions/checkout@v6"

    - name: "First Step"
      run: echo "My First Step..."

    - name: "Second Step: Creating File"
      run: touch newfile.txt

    - name: "Third Step: Listing Files"
      run: ls
